name: Terraform-Plan

on: 
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      WORK_DIR: ./GCP/main/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.WORK_DIR }}
        run: |
          terraform init
          terraform workspace select dev
          terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Terraform Plan
        working-directory: ${{ env.WORK_DIR }}
        run: |
          terraform workspace select dev  
          terraform plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
